server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        hbm2ddl:
#          auto: create
    show-sql: true
  liquibase:
    change-log: 'classpath:/db/changelog-master.yaml'

authentication:
  public-key:
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo5ZsH69FHjKRbsZ3/kTU
    yxrI9/Ob70iDjIbW2++skjGFanSZdw8sirBFQOAjqmVkIfros/+2aZSIiRmNmQ6J
    kb2fXlpCMb/EW4x90nFixsRo56E8e74oSN2KSmqv+EYoqMDO20Xvp2tq/vUtXm5D
    /M9+G0F+1n1tz+DI78Y1X3nWotm8eFAkGH/Ya44gmucOxfMp9C4lBb4Q+26ZCIZH
    1WB9LsEDUQiWmlXulR0LU5CwCQTBiF7U99Ba1w4KfD1QMMqoapVEH/G6uama4IpB
    x9xyZzDbvsT81ye5IuB5fLGKN8KxypnLiXnQS2y5wfXai7duZI9e1rTbIP/a+YJL
    RwIDAQAB
    -----END PUBLIC KEY-----
  private-key:
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAo5ZsH69FHjKRbsZ3/kTUyxrI9/Ob70iDjIbW2++skjGFanSZ
    dw8sirBFQOAjqmVkIfros/+2aZSIiRmNmQ6Jkb2fXlpCMb/EW4x90nFixsRo56E8
    e74oSN2KSmqv+EYoqMDO20Xvp2tq/vUtXm5D/M9+G0F+1n1tz+DI78Y1X3nWotm8
    eFAkGH/Ya44gmucOxfMp9C4lBb4Q+26ZCIZH1WB9LsEDUQiWmlXulR0LU5CwCQTB
    iF7U99Ba1w4KfD1QMMqoapVEH/G6uama4IpBx9xyZzDbvsT81ye5IuB5fLGKN8Kx
    ypnLiXnQS2y5wfXai7duZI9e1rTbIP/a+YJLRwIDAQABAoIBAF30HtVzzLazRGPj
    CTe4QJ8GGzaNa5nag/NJ3k0jMnIkjwO9RAblaCefZacFFHbhFMmPWedHjnTFIkXb
    rz+g4dIanlWKcUoxYY1S+1DKXnjahYXDTQGlDW4MD0j+TWLCqMeDNUsqt6HoR+N2
    3T/HBLVGVp9A1qBKGa+y4rUTmcPjQWAABKgV71FQKa0QYOd1ApEyK4DQKWzaFCo2
    508Brlj86pPUeOLFD2ZIwdTA5cY+Ho7jtbdTZOCtJlzoS572zBlx9QG8ARbu5+Mx
    lTZoTt7S5wzmyfGimT4kJhWk/8PWwv+kqlFJdO0nNMWAzsuieGcv/G8Abuit64lH
    F3qCY4ECgYEA5vlRaAsHLjamji+mV7bq8+FaiRfqrxXpllH1Jz4hxMh2w2PApihI
    vuY/xoh0jmDxRgGif66fKlkSB7FX2tmwAsuMr481/2LrhHUTMzZCrhLR1hDrDEDI
    aWqikhsfXbRP+5U6OMJ53RSl329FAixnR8sraAyt8CdMRdi/bCqkegkCgYEAtU/2
    wDZ57wgaSjLOEAF9QtedRpLW17t2q0aJKJ+CukI2eWuuY9tWb25G9iwWtLlbUHn0
    zpbRDJXOb864CE0qePn1WFJcQbnQaIdWvgOjVMKvtKjhz/qcCFitmtt/c/nZmA8H
    gdwwpcYWsGgBfe7/qiMit2alplbZrFuMqAlmLs8CgYAwGZuqXyGPrjHhSmsJuT4U
    q8l+40wsShPrCgZTtcyyfky9Q/jKoXkEyE5fuesL+4RDX/PHQ0ZCO2pVz8jL+ql8
    64bQyLImDSOe4gKtl48rUSABxGQumQ8jZOGWK6/Mg9BkRB9r0pQuRi6E6VclrLmV
    aeoQMRPH/2cS5KB4lijKgQKBgEEkO6kPaXuh06A45KQHhPOQ9+a1Nw9HQPmEXB8G
    QDefNmclcwBZe5KJcmFbscS4m8AsMPJQaUc2Q3cUNDZ3Uv0oASf8Xz0V/3Suu1GF
    iRcY43vq+UZ56blt8uGiXwZSDAV/0NitPaUxqFE07ORMC/saqIxwCq/aoFY2hjCR
    P+8tAoGBAIhQ1VSLSVQCblaHP2+1IDugl+SRvnWa67W2DWJobZumjvZztoub6ULT
    4zzEVVcrDMc2l46MrZs/17wmfmqyQGW0nYFK3nUS/Ol1GCm+/S65ve9+BtOGM30m
    uCd0U+3zz08zmasz+305NkrmhsfPPTRyd13OhODFq9k+lwRB8JTS
    -----END RSA PRIVATE KEY-----

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
    com:
      arthub:
        userservice:
          service:
            impl: DEBUG
          controller: DEBUG
          config: DEBUG
          auth: DEBUG
          filter: DEBUG
          provider: DEBUG
    feign: TRACE