server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        hbm2ddl:
#          auto: create
    show-sql: true
  liquibase:
    change-log: 'classpath:/db/changelog-master.yaml'

authentication:
  public-key:
    -----BEGIN PUBLIC KEY-----
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCAS+uydez9AqTwffToK7HLDDgJ
    VFBxBEv5bLtWesPY/1DJA2zI3ktn5tzWmAnDLjYF61RK3XAC3xIrfgvYWMZQiyNw
    GnQuzQXLiHw2QfFdycUyL7KXkFRxvIoP7WF6/yqPaZ2GQXAZoJuq8rwFpxjtww7a
    esXui3tZFG1fF9GEFQIDAQAB
    -----END PUBLIC KEY-----
  private-key:
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQCAS+uydez9AqTwffToK7HLDDgJVFBxBEv5bLtWesPY/1DJA2zI
    3ktn5tzWmAnDLjYF61RK3XAC3xIrfgvYWMZQiyNwGnQuzQXLiHw2QfFdycUyL7KX
    kFRxvIoP7WF6/yqPaZ2GQXAZoJuq8rwFpxjtww7aesXui3tZFG1fF9GEFQIDAQAB
    AoGAU5ikoKkkXYvui2GXRfzKoaJ5lOKic7G4C3Mk8mmV2XwrWH9pz8zA15ffR9jT
    a6FdxCedyhZVmRlfDoXYFAVsWjzRq+QXNcUNhoQiwu9zBHNGbA/7mEvUe/G1P6ET
    SBQgwxtyhRFIzSBmTp5Kv55Mc0/2EFRDauDf/AUL/O73ptUCQQC19q8NltQvzaUj
    3RNssNIQlnyyy9z8yIOSSYJGZg/WxzZc5xrl3d3OC8FOlwVSqJ+xCOS13mg7rKOo
    mvmVMBD7AkEAtH9IFKhMy1kpEyY7CHwbDbYT4AXe4P73vNy2Ww0h8I116GdbCOcE
    W0XsbmRhPjcXjm1VklU+DCr6C2fqUkpSLwJBAKl8axLaQSuBfWcJPVWI4TDoKqAT
    OPQPBFYWuAxAdlJUXbNs42XmIPoRgu1jx2Z1f8DTCszHqwiiRhH+v6gRDE8CQB7p
    jZa8HCrXYkl9Sq7xUlDO1iiP2NP/1r3prvF5Fk70azUaPmUP65cWKp/dYSoelVI3
    N2iQYMgEtD4v1dmyENECQBNsW1+IUwoPPwQTtMlD5O8d+3v7YtVeLAQap0NTdHqb
    2uyAEmE+7lwTsjjuY9/Jy2Tza460SwgBkwF/VV1hj6Y=
    -----END RSA PRIVATE KEY-----

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
    com:
      arthub:
        userservice:
          service:
            impl: DEBUG
          controller: DEBUG
    feign: TRACE